#!/bin/bash

set -e

make build

if [[ $# -eq 1 ]]; then
    file_path=$(realpath "$@")
    cd build
    java dev.javarush.ci.lox.Lox "$file_path"
else
    cd build
    java dev.javarush.ci.lox.Lox
fi

